# Generated by Django 5.2.3 on 2025-07-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_personelinterests_user_personalinterests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('developer', 'Developer'), ('contributor', 'Contributor')], default='intern', max_length=20),
        ),
    ]
