# Generated by Django 5.2.3 on 2025-07-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('experts', 'Experts'), ('directors', 'Directors')], default='intern', max_length=20),
        ),
    ]
