# Generated by Django 5.2.3 on 2025-06-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='personelinterests',
            new_name='personalinterests',
        ),
    ]
